### ISSUE TITLE
No maximum value is entered when listing an item.

### ISSUE THREAD

**Issue by Rigaln** [chalkos/Marketbuddy#36]
### What's your suggestion?

When listing stacked items, for some reason a few items are left out and not all of them are listed.
Example
Listing 50 stacked items → 45 items are specified as the default number of items.

**Comment by chalkos** [comment]
There's an option to specify the stack size when posting. if you have that set to 45, it will always use 45 as stack size (unless you have less than 45 -- in that case it will post all of them).

Your suggestion is already implemented. Because you can set the stack size to 99 and it will post your stacks of 50 (or whatever other stack size you have)

**Comment by Rigaln** [comment]
I'm having trouble finding anything but limitstacksize settings.
What should I change so that I can always list the maximum number of items?

**Comment by chalkos** [comment]
change the limitstacksize to 9999
